include local.mk
PROGRAM = fatfs_sdcard_demo
EXTRA_COMPONENTS = \
	$(COMPONENTS_DIR)/fatfs \
	$(COMPONENTS_DIR)/fatfs_sdcard_io \
	$(COMPONENTS_DIR)/sdcard \
	$(COMPONENTS_DIR)/hspi
include $(ESP_OPEN_RTOS_DIR)/common.mk
